import './globals.css';
import { Rubik } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import { InputsContextProvider } from '../components/Context';
import AuthContextProvider from '../components/authContext/AuthContext';
import Script from 'next/script'; // لاستيراد عنصر Script من Next.js
import BackButton from '../components/BackButton';
import SubscribedOrNot from '../components/paypal/subscribedOrNot';
import SideBarMenu from '../components/SideBarMenu';
import SearchHeader from '../components/search-header';
const rubik = Rubik({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth relative" dir="rtl">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={rubik.className}>
        <AuthContextProvider>
          <BackButton />
          <Toaster />
          <SubscribedOrNot />
          {/* <SubscriptionPage/> */}
          <SearchHeader />
          <SideBarMenu />

          <InputsContextProvider>{children}</InputsContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
